name: My success workflow
on: 
    push:
        tags: 
          - v[0-9].[0-9]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
        - 
            name: Checkout
            uses: actions/checkout@v4
        -
            name: Check commit message
            run: |
                nowmessage=$(git log -1 --pretty=%B)
                if [[ $nowmessage == "#NORUN"* ]]; then
                    exit 1
                fi